
variables:
  MAVEN_OPTS: "-Dhttps.protocols=TLSv1.2 -Dmaven.repo.local=$CI_PROJECT_DIR/.m2/repository -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=WARN -Dorg.slf4j.simpleLogger.showDateTime=true -Djava.awt.headless=true"
  MAVEN_CLI_OPTS: "--batch-mode --errors --fail-at-end --show-version -DinstallAtEnd=true -DdeployAtEnd=true"
  MAVEN_USER_HOME: $CI_PROJECT_DIR/.m2

stages:
  - ⬇ download
  - 🧪 test
  - 👷‍ build
  - 🐳 packaging

⬇ backend:
  stage: ⬇ download
  image: openjdk:11-slim
  script:
    - ./mvnw $MAVEN_CLI_OPTS -f backend/pom.xml dependency:resolve dependency:resolve-plugins
  cache:
    key: "$CI_PIPELINE_ID-backend"
    policy: push
    paths:
      - .m2/

⬇ ui-v1:
  stage: ⬇ download
  image: openjdk:8
  script:
    - ./mvnw $MAVEN_CLI_OPTS -f frontend-angularjs/pom.xml frontend:install-node-and-npm frontend:npm@npm-install frontend:jspm@jspm-config frontend:jspm@jspm-install -Djspm_token=$JSPM_GITHUB_AUTH_TOKEN
  cache:
    key: "$CI_PIPELINE_ID-ui-v1"
    policy: push
    paths:
      - frontend-angularjs/node_modules/
      - frontend-angularjs/www/jspm_packages/
      - frontend-angularjs/target/
      - .m2/

⬇ ui-v2:
  stage: ⬇ download
  image: node:11
  script:
    - yarn --cwd frontend-angular
  cache:
    key: "$CI_PIPELINE_ID-ui-v2"
    policy: push
    paths:
      - .yarn
      - frontend-angular/node_modules/

🧪 backend:
  stage: 🧪 test
  image: openjdk:11-slim
  needs: [⬇ backend]
  script:
    - ./mvnw $MAVEN_CLI_OPTS -f backend/pom.xml liquibase:dropAll liquibase:update jooq-codegen:generate test -Ddatabase.url=jdbc:h2:/tmp/podcast-server jacoco:report
    - bash <(curl -s https://codecov.io/bash) -t $CODECOV_TOKEN
  cache:
    key: "$CI_PIPELINE_ID-backend"
    policy: pull
    paths:
      - .m2/

🧪 ui-v2:
  stage: 🧪 test
  image: node:11
  needs: [⬇ ui-v2]
  script:
    - yarn --cwd frontend-angular test
  cache:
    key: "$CI_PIPELINE_ID-ui-v2"
    policy: pull
    paths:
      - .yarn
      - frontend-angular/node_modules/

👷 backend-base-image:
  stage: 👷‍ build
  needs: [⬇ backend]
  image:
    name: gcr.io/kaniko-project/executor:debug
    entrypoint: [""]
  before_script:
    - echo "{\"auths\":{\"index.docker.io\":{\"username\":\"$DOCKER_IO_USER\",\"password\":\"$DOCKER_IO_PASSWORD\"}}}" > /kaniko/.docker/config.json
  script:
    - /kaniko/executor --context $CI_PROJECT_DIR --dockerfile $CI_PROJECT_DIR/backend/src/main/docker/base-image/Dockerfile --destination podcastserver/backend-base-image:${CI_COMMIT_TAG:-$CI_COMMIT_REF_SLUG}

👷 backend:
  stage: 👷‍ build
  image: openjdk:11-slim
  needs: [🧪 backend]
  script:
    - ./mvnw $MAVEN_CLI_OPTS -f backend/pom.xml liquibase:dropAll liquibase:update jooq-codegen:generate compile
  artifacts:
    paths:
      - backend/target
  cache:
    key: "$CI_PIPELINE_ID-backend"
    policy: pull-push
    paths:
      - .m2/

👷 ui-v1:
  stage: 👷‍ build
  image: openjdk:8
  needs: [⬇ ui-v1]
  script:
    - ./mvnw $MAVEN_CLI_OPTS -f frontend-angularjs/pom.xml frontend:gulp@build-less frontend:gulp@build-app
  artifacts:
    paths:
      - frontend-angularjs/target/dist/
  cache:
    key: "$CI_PIPELINE_ID-ui-v1"
    policy: pull
    paths:
      - frontend-angularjs/node_modules/
      - frontend-angularjs/www/jspm_packages/
      - frontend-angularjs/target/

👷 ui-v2:
  stage: 👷‍ build
  image: node:11
  needs: [⬇ ui-v2]
  script:
    - yarn --cwd frontend-angular build
  artifacts:
    paths:
      - frontend-angular/dist/
  cache:
    key: "$CI_PIPELINE_ID-ui-v2"
    policy: pull
    paths:
      - .yarn
      - frontend-angular/node_modules/

🐳 backend:
  stage: 🐳 packaging
  image: openjdk:11-slim
  needs: [👷 backend, 👷 backend-base-image]
  before_script:
  script:
    - ./mvnw $MAVEN_CLI_OPTS -f backend/pom.xml jib:build -Dtag=${CI_COMMIT_TAG:-$CI_COMMIT_REF_SLUG} -Dbase-image-tag=${CI_COMMIT_TAG:-$CI_COMMIT_REF_SLUG}
    - if [ "$CI_COMMIT_REF_SLUG" == "master" ]; then ./mvnw $MAVEN_CLI_OPTS -f backend/pom.xml jib:build -Dtag=latest -Dbase-image-tag=${CI_COMMIT_TAG:-$CI_COMMIT_REF_SLUG} ; fi
  cache:
    key: "$CI_PIPELINE_ID-backend"
    policy: pull
    paths:
      - .m2/

🐳 file-system:
  stage: 🐳 packaging
  needs: [⬇ backend]
  image:
    name: gcr.io/kaniko-project/executor:debug
    entrypoint: [""]
  before_script:
    - echo "{\"auths\":{\"index.docker.io\":{\"username\":\"$DOCKER_IO_USER\",\"password\":\"$DOCKER_IO_PASSWORD\"}}}" > /kaniko/.docker/config.json
  script:
    - sh ./files-system/compile.sh
    - export VERSION="${CI_COMMIT_TAG:-$CI_COMMIT_REF_SLUG}"
    - export PROJECT_DIR=$CI_PROJECT_DIR/files-system/target/docker/
    - /kaniko/executor --context $PROJECT_DIR --dockerfile $CI_PROJECT_DIR/files-system/target/docker/Dockerfile --destination podcastserver/file-system:${VERSION}
    - if [ "$VERSION" == "master" ]; then /kaniko/executor --context $PROJECT_DIR --dockerfile $CI_PROJECT_DIR/files-system/target/docker/Dockerfile --destination podcastserver/file-system:latest ; fi

🐳 ui:
  stage: 🐳 packaging
  needs: [👷 ui-v1, 👷 ui-v2, 🧪 ui-v2]
  image:
    name: gcr.io/kaniko-project/executor:debug
    entrypoint: [""]
  before_script:
    - echo "{\"auths\":{\"index.docker.io\":{\"username\":\"$DOCKER_IO_USER\",\"password\":\"$DOCKER_IO_PASSWORD\"}}}" > /kaniko/.docker/config.json
  script:
    - sh ./ui/compile.sh
    - export VERSION="${CI_COMMIT_TAG:-$CI_COMMIT_REF_SLUG}"
    - export PROJECT_DIR=$CI_PROJECT_DIR/ui/target/docker/
    - /kaniko/executor --context $PROJECT_DIR --dockerfile $CI_PROJECT_DIR/ui/target/docker/Dockerfile --destination podcastserver/ui:${VERSION}
    - if [ "$VERSION" == "master" ]; then /kaniko/executor --context $PROJECT_DIR --dockerfile $CI_PROJECT_DIR/files-system/target/docker/Dockerfile --destination podcastserver/ui:latest ; fi
