
variables:
  MAVEN_OPTS: "-Dhttps.protocols=TLSv1.2 -Dmaven.repo.local=$CI_PROJECT_DIR/.m2/repository -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=WARN -Dorg.slf4j.simpleLogger.showDateTime=true -Djava.awt.headless=true"
  MAVEN_CLI_OPTS: "--batch-mode --errors --fail-at-end --show-version -DinstallAtEnd=true -DdeployAtEnd=true"
  MAVEN_USER_HOME: $CI_PROJECT_DIR/.m2

.cicd_utils: &cicd_utils |
  function delete_docker_hub_image() {
    COMPONENT=$1
    JWT_TOKEN=$(curl -s -H 'Content-Type: application/json' -d '{"username": "'${DOCKER_IO_USER}'", "password": "'${DOCKER_IO_PASSWORD}'"}' https://hub.docker.com/v2/users/login/ | sed 's@.*token": "\([^"]*\)".*@\1@g')
    curl -L -X DELETE -H "Authorization: JWT $JWT_TOKEN" https://hub.docker.com/v2/repositories/podcastserver/$COMPONENT/tags/$CI_COMMIT_REF_SLUG/
  }


stages:
  - ⬇ download
  - 🧪 test
  - 👷‍ build
  - 🐳 packaging
  - 🔎 Security Analysis

⬇ container analysis db:
  stage: ⬇ download
  image:
    name: aquasec/trivy
    entrypoint: [""]
  script:
    - trivy --download-db-only --no-progress --cache-dir .trivy/
  cache:
    key: trivy-database
    paths:
      - .trivy

⬇ backend:
  stage: ⬇ download
  image: openjdk:11-slim
  script:
    - ./mvnw $MAVEN_CLI_OPTS -f backend/pom.xml dependency:resolve dependency:resolve-plugins
  cache:
    key:
      files:
        - backend/pom.xml
      prefix: "backend"
    paths:
      - .m2/

⬇ ui-v1:
  stage: ⬇ download
  image: openjdk:8
  script:
    - ./mvnw $MAVEN_CLI_OPTS -f frontend-angularjs/pom.xml frontend:install-node-and-npm frontend:npm@npm-install frontend:jspm@jspm-config frontend:jspm@jspm-install -Djspm_token=$JSPM_GITHUB_AUTH_TOKEN
  cache:
    key:
      files:
        - frontend-angularjs/npm-shrinkwrap.json
        - frontend-angularjs/www/config.js
      prefix: "ui-v1"
    paths:
      - frontend-angularjs/node_modules/
      - frontend-angularjs/www/jspm_packages/
      - frontend-angularjs/target/
      - .m2/

⬇ ui-v2:
  stage: ⬇ download
  image: node:11
  script:
    - yarn --cwd frontend-angular
  cache:
    key:
      files:
        - frontend-angular/yarn.lock
      prefix: "ui-v2"
    paths:
      - .yarn
      - frontend-angular/node_modules/

🧪 backend:
  stage: 🧪 test
  image: openjdk:11
  needs: [⬇ backend]
  script:
    - ./mvnw $MAVEN_CLI_OPTS -f backend/pom.xml liquibase:dropAll liquibase:update jooq-codegen:generate test -Ddatabase.url=jdbc:h2:/tmp/podcast-server jacoco:report
    - bash <(curl -s https://codecov.io/bash) -t $CODECOV_TOKEN
  cache:
    key:
      files:
        - backend/pom.xml
      prefix: "backend"
    policy: pull
    paths:
      - .m2/

🧪 ui-v2:
  stage: 🧪 test
  image: node:11
  needs: [⬇ ui-v2]
  script:
    - yarn --cwd frontend-angular test
  cache:
    key:
      files:
        - frontend-angular/yarn.lock
      prefix: "ui-v2"
    policy: pull
    paths:
      - .yarn
      - frontend-angular/node_modules/

👷 backend-base-image:
  stage: 👷‍ build
  needs: [⬇ backend]
  image:
    name: gcr.io/kaniko-project/executor:debug
    entrypoint: [""]
  before_script:
    - echo "{\"auths\":{\"index.docker.io\":{\"username\":\"$DOCKER_IO_USER\",\"password\":\"$DOCKER_IO_PASSWORD\"}}}" > /kaniko/.docker/config.json
  script:
    - /kaniko/executor --context $CI_PROJECT_DIR --dockerfile $CI_PROJECT_DIR/backend/src/main/docker/base-image/Dockerfile --destination podcastserver/backend-base-image:${CI_COMMIT_TAG:-$CI_COMMIT_REF_SLUG}

👷 backend:
  stage: 👷‍ build
  image: openjdk:11-slim
  needs: [🧪 backend]
  script:
    - ./mvnw $MAVEN_CLI_OPTS -f backend/pom.xml liquibase:dropAll liquibase:update jooq-codegen:generate compile
  artifacts:
    paths:
      - backend/target
  cache:
    key:
      files:
        - backend/pom.xml
      prefix: "backend"
    paths:
      - .m2/

👷 ui-v1:
  stage: 👷‍ build
  image: openjdk:8
  needs: [⬇ ui-v1]
  script:
    - ./mvnw $MAVEN_CLI_OPTS -f frontend-angularjs/pom.xml frontend:gulp@build-less frontend:gulp@build-app
  artifacts:
    paths:
      - frontend-angularjs/target/dist/
  cache:
    key:
      files:
        - frontend-angularjs/npm-shrinkwrap.json
        - frontend-angularjs/www/config.js
      prefix: "ui-v1"
    policy: pull
    paths:
      - frontend-angularjs/node_modules/
      - frontend-angularjs/www/jspm_packages/
      - frontend-angularjs/target/

👷 ui-v2:
  stage: 👷‍ build
  image: node:11
  needs: [⬇ ui-v2]
  script:
    - yarn --cwd frontend-angular build
  artifacts:
    paths:
      - frontend-angular/dist/
  cache:
    key:
      files:
        - frontend-angular/yarn.lock
      prefix: "ui-v2"
    policy: pull
    paths:
      - .yarn
      - frontend-angular/node_modules/

🐳 backend:
  stage: 🐳 packaging
  image: openjdk:11-slim
  needs: [👷 backend, 👷 backend-base-image]
  script:
    - ./mvnw $MAVEN_CLI_OPTS -f backend/pom.xml jib:build -Dtag=${CI_COMMIT_TAG:-$CI_COMMIT_REF_SLUG} -Dbase-image-tag=${CI_COMMIT_TAG:-$CI_COMMIT_REF_SLUG}
    - if [ "$CI_COMMIT_REF_SLUG" == "master" ]; then ./mvnw $MAVEN_CLI_OPTS -f backend/pom.xml jib:build -Dtag=latest -Dbase-image-tag=${CI_COMMIT_TAG:-$CI_COMMIT_REF_SLUG} ; fi
  cache:
    key:
      files:
        - backend/pom.xml
      prefix: "backend"
    policy: pull
    paths:
      - .m2/
  environment:
    name: backend/$CI_COMMIT_REF_SLUG
    url: https://cloud.docker.com/u/podcastserver/repository/docker/podcastserver/backend/tags
    on_stop: 🗑 backend

🗑 backend:
  stage: 🐳 packaging
  image: tutum/curl
  dependencies: []
  variables:
    GIT_STRATEGY: none
  before_script:
    - *cicd_utils
  script:
    - delete_docker_hub_image backend
    - delete_docker_hub_image backend-base-image
  when: manual
  environment:
    name: backend/$CI_COMMIT_REF_SLUG
    action: stop

🐳 file-system:
  stage: 🐳 packaging
  needs: [⬇ backend]
  image:
    name: gcr.io/kaniko-project/executor:debug
    entrypoint: [""]
  before_script:
    - echo "{\"auths\":{\"index.docker.io\":{\"username\":\"$DOCKER_IO_USER\",\"password\":\"$DOCKER_IO_PASSWORD\"}}}" > /kaniko/.docker/config.json
  script:
    - sh ./files-system/compile.sh
    - export VERSION="${CI_COMMIT_TAG:-$CI_COMMIT_REF_SLUG}"
    - export PROJECT_DIR=$CI_PROJECT_DIR/files-system/target/docker/
    - /kaniko/executor --context $PROJECT_DIR --dockerfile $PROJECT_DIR/Dockerfile --destination podcastserver/file-system:${VERSION}
    - if [ "$VERSION" == "master" ]; then /kaniko/executor --context $PROJECT_DIR --dockerfile $PROJECT_DIR/Dockerfile --destination podcastserver/file-system:latest ; fi
  environment:
    name: file-system/$CI_COMMIT_REF_SLUG
    url: https://cloud.docker.com/u/podcastserver/repository/docker/podcastserver/file-system/tags
    on_stop: 🗑 file-system

🗑 file-system:
  stage: 🐳 packaging
  image: tutum/curl
  dependencies: []
  variables:
    GIT_STRATEGY: none
  before_script:
    - *cicd_utils
  script:
    - backend-base-image file-system
  when: manual
  environment:
    name: file-system/$CI_COMMIT_REF_SLUG
    action: stop

🐳 ui:
  stage: 🐳 packaging
  needs: [👷 ui-v1, 👷 ui-v2, 🧪 ui-v2]
  image:
    name: gcr.io/kaniko-project/executor:debug
    entrypoint: [""]
  before_script:
    - echo "{\"auths\":{\"index.docker.io\":{\"username\":\"$DOCKER_IO_USER\",\"password\":\"$DOCKER_IO_PASSWORD\"}}}" > /kaniko/.docker/config.json
  script:
    - sh ./ui/compile.sh
    - export VERSION="${CI_COMMIT_TAG:-$CI_COMMIT_REF_SLUG}"
    - export PROJECT_DIR=$CI_PROJECT_DIR/ui/target/docker/
    - /kaniko/executor --context $PROJECT_DIR --dockerfile $PROJECT_DIR/Dockerfile --destination podcastserver/ui:${VERSION}
    - if [ "$VERSION" == "master" ]; then /kaniko/executor --context $PROJECT_DIR --dockerfile $PROJECT_DIR/Dockerfile --destination podcastserver/ui:latest ; fi
  environment:
    name: ui/$CI_COMMIT_REF_SLUG
    url: https://cloud.docker.com/u/podcastserver/repository/docker/podcastserver/ui/tags
    on_stop: 🗑 ui

🗑 ui:
  stage: 🐳 packaging
  image: tutum/curl
  dependencies: []
  variables:
    GIT_STRATEGY: none
  before_script:
    - *cicd_utils
  script:
    - backend-base-image ui
  when: manual
  environment:
    name: ui/$CI_COMMIT_REF_SLUG
    action: stop

🔎 backend:
  stage: 🔎 Security Analysis
  image:
    name: aquasec/trivy
    entrypoint: [""]
  needs: [⬇ container analysis db, 🐳 backend]
  script:
    - trivy --exit-code 0 --no-progress --cache-dir .trivy/ --format template --template "@.ci/gitlab-trivy.tpl" -o gl-container-scanning-report.json podcastserver/backend:${CI_COMMIT_TAG:-$CI_COMMIT_REF_SLUG}
    - trivy --exit-code 0 --no-progress --cache-dir .trivy/ podcastserver/backend:${CI_COMMIT_TAG:-$CI_COMMIT_REF_SLUG}
  artifacts:
    reports:
      container_scanning: gl-container-scanning-report.json
  cache:
    key: trivy-database
    policy: pull
    paths:
      - .trivy

🔎 file-system:
  stage: 🔎 Security Analysis
  image:
    name: aquasec/trivy
    entrypoint: [""]
  needs: [⬇ container analysis db, 🐳 file-system]
  script:
    - trivy --exit-code 0 --no-progress --cache-dir .trivy/ --format template --template "@.ci/gitlab-trivy.tpl" -o gl-container-scanning-report.json podcastserver/file-system:${CI_COMMIT_TAG:-$CI_COMMIT_REF_SLUG}
    - trivy --exit-code 0 --no-progress --cache-dir .trivy/ podcastserver/file-system:${CI_COMMIT_TAG:-$CI_COMMIT_REF_SLUG}
  artifacts:
    reports:
      container_scanning: gl-container-scanning-report.json
  cache:
    key: trivy-database
    policy: pull
    paths:
      - .trivy

🔎 ui:
  stage: 🔎 Security Analysis
  image:
    name: aquasec/trivy
    entrypoint: [""]
  needs: [⬇ container analysis db, 🐳 ui]
  script:
    - trivy --exit-code 0 --no-progress --cache-dir .trivy/ --format template --template "@.ci/gitlab-trivy.tpl" -o gl-container-scanning-report.json podcastserver/ui:${CI_COMMIT_TAG:-$CI_COMMIT_REF_SLUG}
    - trivy --exit-code 0 --no-progress --cache-dir .trivy/ podcastserver/ui:${CI_COMMIT_TAG:-$CI_COMMIT_REF_SLUG}
  artifacts:
    reports:
      container_scanning: gl-container-scanning-report.json
  cache:
    key: trivy-database
    policy: pull
    paths:
      - .trivy
