apiVersion: skaffold/v1beta13
kind: Config
build:
  artifacts:
    - image: podcastserver/backend
      context: backend
      jibMaven:
        args:
          - liquibase:dropAll
          - liquibase:update
          - jooq-codegen:generate
          - compile
          - -Dmaven.test.skip
    - image: podcastserver/ui-v1
      context: frontend-angularjs/target/
deploy:
  kustomize:
    path: backend/src/main/k8s/docker-for-mac/
