apiVersion: skaffold/v2beta3
kind: Config
build:
  artifacts:
    - image: podcastserver/backend
      context: backend
      jib:
        args:
          - liquibase:dropAll
          - liquibase:update
          - -Dmaven.test.skip
          - -P skaffold
    - image: podcastserver/ui-v1
      context: frontend-angularjs/target/
    - image: podcastserver/init-db
      docker:
        dockerfile: ./backend/src/main/database/Dockerfile
deploy:
  kustomize:
    paths:
      - deployment/kubernetes/docker-for-desktop/
