apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component

resources:
  - database.yaml

configMapGenerator:
  - name: database
    behavior: merge
    literals:
      - username=podcast-server-user
      - name=podcast-server
