apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: minio-console
spec:
  rules:
    - host: to-be-replaced
      http:
        paths:
          - pathType: Prefix
            path: /
            backend:
              service:
                name: storage
                port:
                  number: 9001
