apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  template:
    spec:
      containers:
        - name: app
          volumeMounts:
            - name: podcasts-files
              mountPath: /podcasts
      volumes:
        - name: podcasts-files
          hostPath:
            path: /tmp/podcast-server/files/
            type: DirectoryOrCreate
