apiVersion: v1
kind: Service
metadata:
  name: backend
  labels:
    app: podcast-server
    module: backend
spec:
  ports:
    - name: http-backend-port
      port: 8080
      targetPort: 8080
      protocol: TCP
  selector:
    app: podcast-server
    module: backend
    serving: "true"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  selector:
    matchLabels:
      app: podcast-server
      module: backend
      serving: "true"
  template:
    metadata:
      labels:
        app: podcast-server
        module: backend
        serving: "true"
    spec:
      initContainers:
        - name: init-db
          image: podcastserver/init-db
          env:
            - name: FLYWAY_URL
              valueFrom:
                configMapKeyRef:
                  name: podcast-server
                  key: database.url
            - name: FLYWAY_USER
              valueFrom:
                configMapKeyRef:
                  name: podcast-server
                  key: database.username
            - name: FLYWAY_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: podcast-server
                  key: database.password
      containers:
        - name: app
          image: podcastserver/backend
          env:
            - name: SPRING_DATASOURCE_URL
              valueFrom:
                configMapKeyRef:
                  name: podcast-server
                  key: database.url
            - name: SPRING_DATASOURCE_USERNAME
              valueFrom:
                configMapKeyRef:
                  name: podcast-server
                  key: database.username
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: podcast-server
                  key: database.password
            - name: PODCASTSERVER_API_YOUTUBE
              valueFrom:
                secretKeyRef:
                  optional: true
                  name: podcast-server
                  key: api.youtube
            - name: PODCASTSERVER_ROOTFOLDER
              valueFrom:
                configMapKeyRef:
                  optional: true
                  name: podcast-server
                  key: root-folder
            - name: PODCASTSERVER_CONCURRENT_DOWNLOAD
              valueFrom:
                configMapKeyRef:
                  optional: true
                  name: podcast-server
                  key: concurrent-download
            - name: PODCASTSERVER_MAX_UPDATE_PARALLELS
              valueFrom:
                configMapKeyRef:
                  optional: true
                  name: podcast-server
                  key: max-update-parallels
            - name: PODCASTSERVER_NUMBER_OF_DAY_TO_DOWNLOAD
              valueFrom:
                configMapKeyRef:
                  optional: true
                  name: podcast-server
                  key: number-of-day-to-download
            - name: PODCASTSERVER_NUMBER_OF_DAY_TO_SAVE_COVER
              valueFrom:
                configMapKeyRef:
                  optional: true
                  name: podcast-server
                  key: number-of-day-to-save-cover
          ports:
            - name: http-port
              containerPort: 8080
              protocol: TCP
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
---
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: update-and-download
spec:
  schedule: "0 * * * *"
  successfulJobsHistoryLimit: 1
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: podcast-server-update-and-download
              image: curlimages/curl
              args:
                - /bin/sh
                - -c
                - curl -qsL http://backend:8080/api/v1/podcasts/update?download=true
          restartPolicy: OnFailure
---
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: delete-old-covers
spec:
  schedule: "30 4 * * *"
  successfulJobsHistoryLimit: 1
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: podcast-server-delete-old-covers
              image: curlimages/curl
              args:
                - /bin/sh
                - -c
                - curl -qsL -X DELETE http://backend:8080/api/v1/covers
          restartPolicy: OnFailure
---
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: delete-old-items
spec:
  schedule: "30 5 * * *"
  successfulJobsHistoryLimit: 1
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: podcast-server-delete-old-items
              image: curlimages/curl
              imagePullPolicy: IfNotPresent
              args:
                - /bin/sh
                - -c
                - curl -qsL -X DELETE http://backend:8080/api/v1/items
          restartPolicy: OnFailure
