apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - backend.yaml
  - ui-v1.yaml
  - ui-v2.yaml

configMapGenerator:
  - name: podcast-server
  - name: database
  - name: storage

secretGenerator:
  - name: podcast-server
  - name: database
  - name: storage
