apiVersion: v1
kind: Service
metadata:
  name: ui-v1
  labels:
    app: podcast-server
    module: frontend
    version: v1
spec:
  ports:
    - name: http
      port: 8080
      targetPort: http
      protocol: TCP
  selector:
    app: podcast-server
    module: frontend
    version: v1
    serving: "true"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ui-v1
spec:
  selector:
    matchLabels:
      app: podcast-server
      module: frontend
      version: v1
      serving: "true"
  template:
    metadata:
      labels:
        app: podcast-server
        module: frontend
        version: v1
        serving: "true"
    spec:
      containers:
        - image: podcastserver/ui:latest
          imagePullPolicy: IfNotPresent
          name: ui
          readinessProbe:
            httpGet:
              path: /
              port: http
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
