apiVersion: apps/v1
kind: Deployment
metadata:
  name: storage
spec:
  template:
    spec:
      containers:
        - name: minio
          volumeMounts:
            - name: data
              mountPath: "/data"
      volumes:
        - name: data
          hostPath:
            path: /tmp/podcast-server/files/
            type: DirectoryOrCreate
