apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ingress.yaml

secretGenerator:
  - name: podcast-k8s-local
    files:
      - podcast.k8s.local/tls.crt
      - podcast.k8s.local/tls.key
    type: kubernetes.io/tls
  - name: minio-podcast-k8s-local
    files:
      - minio.podcast.k8s.local/tls.crt
      - minio.podcast.k8s.local/tls.key
    type: kubernetes.io/tls
