apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ingress.yaml

secretGenerator:
  - name: certificates-k8s-local
    files:
      - tls.crt
      - tls.key
    type: kubernetes.io/tls
