apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: podcast-server

resources:
  - ../base/
  - ui/ui-v1.yaml
  - ingress/ingress.yaml

patchesStrategicMerge:
  - backend/backend.yaml
  - database/database.yaml
  - files-system/fs.yaml
  - ingress/ingress.yaml

secretGenerator:
  - name: podcast-k8s-local
    files:
      - ingress/podcast.k8s.local/tls.crt
      - ingress/podcast.k8s.local/tls.key
    type: kubernetes.io/tls
  - name: minio-podcast-k8s-local
    files:
      - ingress/minio.podcast.k8s.local/tls.crt
      - ingress/minio.podcast.k8s.local/tls.key
    type: kubernetes.io/tls
  - name: database
    literals:
      - password=nAAdo5wNs7WEF1UxUobpJDfS9Si62PHa
  - name: podcast-server
    behavior: merge
    literals:
      - api.youtube=TO_BE_DEFINED
    type: Opaque
  - name: storage
    literals:
      - password=Mns1G6RgPtLgy68H

replacements:
  - source:
      kind: Ingress
      name: podcast-server
      fieldPath: spec.rules.0.host
    targets:
      - select:
          kind: Deployment
          name: fs
        fieldPaths:
          - spec.template.spec.containers.[name=minio].env.[name=MINIO_DOMAIN].value
  - source:
      kind: Ingress
      name: minio-console
      fieldPath: spec.rules.0.host
    targets:
      - select:
          kind: Deployment
          name: fs
        fieldPaths:
          - spec.template.spec.containers.[name=minio].env.[name=MINIO_DOMAIN].value
