apiVersion: apps/v1
kind: Deployment
metadata:
  name: podcast-server
spec:
  template:
    spec:
      containers:
        - name: app
          env:
            - name: PODCASTSERVER_API_YOUTUBE
              valueFrom:
                secretKeyRef:
                  name: podcast-server
                  key: api.youtube
          volumeMounts:
            - name: podcast-server-config
              mountPath: /application.yaml
              subPath: application.yaml
            - name: podcasts-files
              mountPath: /podcasts
      volumes:
        - name: podcast-server-config
          configMap:
            name: podcast-server
        - name: podcasts-files
          hostPath:
            path: /tmp/podcast-server/files/
            type: Directory
