apiVersion: v1
kind: Service
metadata:
  name: backend-headless
  labels:
    app: podcast-server
spec:
  clusterIP: None
  ports:
    - name: http-podcast-server-port
      port: 8080
      targetPort: 8080
      protocol: TCP
  selector:
    app: podcast-server
    module: backend
    serving: "true"
