apiVersion: apps/v1
kind: Deployment
metadata:
  name: database
spec:
  template:
    spec:
      containers:
        - name: database
          env:
            - name: POSTGRES_DB
              value: podcast-server-k8s
      volumes:
        - name: database
          hostPath:
            path: /tmp/podcast-server/database/
            type: Directory
---
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: database-backup
spec:
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: database-backup
              env:
              - name: POSTGRES_DB
                value: podcast-server-k8s
          volumes:
            - name: backup
              hostPath:
                path: /tmp/podcast-server/database/backup/
                type: Directory
