apiVersion: v1
kind: Service
metadata:
  name: ui-v1
  labels:
    app: ui-v1
spec:
  ports:
    - name: http-nginx-port
      port: 80
      targetPort: 80
      protocol: TCP
  selector:
    app: ui-v1
    module: frontend
    serving: "true"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ui-v1
spec:
  selector:
    matchLabels:
      app: ui-v1
      module: frontend
      serving: "true"
  template:
    metadata:
      labels:
        app: ui-v1
        module: frontend
        serving: "true"
    spec:
      containers:
        - image: podcastserver/ui-v1
          imagePullPolicy: IfNotPresent
          name: ui-v1
          readinessProbe:
            httpGet:
              path: /
              port: 80
          ports:
            - name: http-port
              containerPort: 80
              protocol: TCP
