apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: podcast-server

resources:
  - git::https://gitlab.com/davinkevin/home-server.git//podcast-server/base/
  - ui-v1.yaml

patchesStrategicMerge:
  - backend.yaml
  - database.yaml
  - fs.yaml
  - ingress.yaml

configMapGenerator:
  - name: podcast-server
    files:
      - application.yaml
    literals:
      - database.username=podcast-server-user
      - database.url=jdbc:postgresql://database:5432/podcast-server-k8s

secretGenerator:
  - name: podcast-server-tls
    files:
      - ingress/tls.crt
      - ingress/tls.key
    type: kubernetes.io/tls
  - literals:
      - database.password=nAAdo5wNs7WEF1UxUobpJDfS9Si62PHa
      - api.youtube=AN_API_KEY
    name: podcast-server
    type: Opaque
