apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: podcast-server-example

bases:
  - ../standard

patchesStrategicMerge:
  - storage/backend.storage.yaml
  - storage/database.storage.yaml
  - storage/fs.storage.yaml
