##############################
#       Spring Config        #
##############################

spring:
 h2.console.enabled: true
 mvc.view:
  suffix: .html
  prefix: /
 datasource:
  url: jdbc:h2:mem:exampledb
  username: foo
  password: bar
  driver-class-name: org.h2.Driver
 servlet.multipart:
  location: /tmp/podcast-server/
  max-file-size: 512MB
  max-request-size: 512MB

server:
 port: 8080
 compression:
  enabled: true
  mime-types: application/json,application/xml,text/html,text/xml,text/plain

logging:
 file:
  path: /tmp/podcast-server/podcast-server.log

management.endpoint.health.show-details: always

##############################
#    Application Specific    #
##############################

podcastserver:
 rootfolder: /tmp
 concurrent-download: 3
 max-update-parallels: 256
 cover-default-name: cover
 number-of-day-to-download: 30
 number-of-day-to-save-cover: 30
 #number-of-try: 10
 #download-extension: .psdownload
 #rss-default-number-item: 50
 externaltools:
  #rtmpdump: /usr/local/bin/rtmpdump
  #ffmpeg: /usr/local/bin/ffmpeg
  #ffprobe: /usr/local/bin/ffprobe
 api :
  youtube : YOUR_API_KEY_OR_EMPTY_IF_NO_ONE
