##############################
#       Spring Config        #
##############################

spring:
 h2.console.enabled: true
 datasource:
  url: jdbc:h2:/tmp/podcast-server
  username: sa
  driver-class-name: org.h2.Driver
 servlet.multipart:
  location: ${java.io.tmpdir}
  max-file-size: 512MB
  max-request-size: 512MB
 codec:
  max-in-memory-size: 500MB

server:
 port: 8080

logging:
 level:
  lan.dk.podcastserver : DEBUG
 file:
  path: /tmp/podcast-server/podcast-server.log

management:
  endpoint:
    health.show-details: always
  endpoints.web.exposure.include: ['health', 'info', 'env']


##############################
#    Application Specific    #
##############################

podcastserver:
 rootfolder: /tmp/podcast-server/
 #concurrent-download: 2
 max-update-parallels: 256
 #cover-default-name: cover
 #number-of-try: 10
 #download-extension: .psdownload
 #rss-default-number-item: 50
 externaltools:
  #rtmpdump: /usr/local/bin/rtmpdump
  #ffmpeg: /usr/local/bin/ffmpeg
  #ffprobe: /usr/local/bin/ffprobe
