apiVersion: v1
kind: ConfigMap
metadata:
  name: build
  annotations:
    config.kubernetes.io/function: |
      container:
        image: gcr.io/kpt-functions/kustomize-build
        network:
          required: true
data:
  path: /source
