apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component

resources:
  - storage.yaml

patchesStrategicMerge:
  - backend-set-internal-storage.yaml

configMapGenerator:
  - name: storage
    behavior: merge
    literals:
      - username=podcast-server-user
      - bucket=data
      - url=http://storage:9000/
